### PR TITLE
#40 Added support loggers.appender to route different loggers to diff…

### PR DESCRIPTION
**Pull request by const1993**
…erent files

### CODE REVIEW

**Comment by andrus** [comment]
@const1993 Can you please write a description of this solution from a user perspective, either here or in #40 ?

**Comment by const1993** [comment]
log:
  level: error
  appenderRefs:
  - appenderRoot
  loggers:
    one: 								
      level: info
      appenderRefs:
      - appenderOne
      - appenderTwo
    two:     
      level: warn
      appenderRefs:
      - appenderTwo
    three: 
      level: trace

  appenders:
    - type: file
      name: appenderOne
      logFormat: '%c{20}: %m%n'
      file: target/logback/one.log
    - type: file
      name: appenderTwo
      logFormat: '%c{20}: %m%n'
      file: target/logback/two.log
    - type: file
      name: appenderRoot
      logFormat: '%c{20}: %m%n'
      file: target/logback/root.log
    - type: file
      logFormat: '%c{20}: %m%n'
      file: target/logback/all.log

- LoggerFactory. getLogger ("one"); - will write with all root appenders ("appeenderRoot" and unnamed appender), "appenderOne" and "appenderTwo" under the info level
- LoggerFactory. getLogger ("two"); - will write with all root appenders ("appeenderRoot" and unnamed appender) and "appenderTwo" under the warn level
- LoggerFactory. getLogger ("three"); - will write with only root appenders ("appeenderRoot" and unnamed appender) because it doesn't have any offenders
- All other loggers will write with "appenerRoot" and unnamed appended under the error level, which is added to the root logger level.

**Comment by andrus** [comment]
Thanks for the explanation. Understood. 

My other concern is `AppenderWithFlag` and the surrounding bootstrap code. Is the purpose to avoid starting the same appender twice and to avoid starting unused appenders at all? Perhaps this can be done by collecting the references first, then starting the appenders, then assigning them to loggers?

**Comment by const1993** [comment]
Yes it make sence. I made some optimisations according to your recomendations. Now named appenders with references will be created ones and then will be assigned to loggers. Named appenders without references will not be created. Unnamed appenders will be assigned to root logger as it was in original logback.

**Comment by andrus** [comment]
I ended up doing quite a bit of refactoring on top of the pull request. I wanted clarity on what happens in the config method, so now it looks like this, which I hope is more transparent:

```java
Map<String, Appender<ILoggingEvent>> namedAppenders = createNamedAppenders(context);
Collection<Appender<ILoggingEvent>> anonAppenders = createAnonymousAppenders(context);

// do not pass anonymous appenders to the child logger, only use them with the root logger
loggers.forEach((name, lf) -> lf.configLogger(context.getLogger(name), namedAppenders, Collections.emptyList()));
rootLoggerFactory.configLogger(context.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME), namedAppenders, anonAppenders);

```

**Pull request merged**
